version: '3.2'
services:
  backend1:
    image: nginx
  backend2:
    image: nginx

  loadbalancer:
      image: nginx
      volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf"
      depends_on:
          - backend1
          - backend2
      ports:
          - '8080:8080'
volumes:
  backend:
